spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
  h2:
    console:
      enabled: true

cloud:
  aws:
    credentials:
      accessKey: web-clipboard
      secretKey: password
    region.static: us-east-1
    stack:
      auto: false

my-app:
  aws:
    service-endpoint: http://localhost:9000