cloud:
  aws:
    credentials:
      accessKey: web-clipboard
      secretKey: password
    region.static: us-east-1
    stack:
      auto: false

my-app:
  aws:
    service-endpoint: http://localhost:9000