name: Docker Image Build and Deploy
on:
  workflow_dispatch: {}
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build with Gradle
        run: ./gradlew build -x test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webly:${{ github.sha }}
          cache-from : type=gha
          cache-to : type=gha,mode=max
  update-argocd-tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.ARGOCD_REPO }}
          ref: "release"
          token: ${{ secrets.ARGOCD_REPO_TOKEN }}
      - name: change values-dev.yaml
        run: |
          sed -i 's/image:.*/image: ${{ secrets.DOCKERHUB_USERNAME }}\/webly:${{ github.sha }}/' oci/argocd/webly/webly.yaml
      - name: git push
        run: |
          git config --global user.email "webly314@github.com"
          git config --global user.name "webly314"
          git add .
          git commit -m "[Webly] dev server update image tag"
          git pull origin release
          git push origin release
